FROM vllm/vllm-openai:v0.11.0
ENTRYPOINT []

RUN ln -sf /usr/bin/python3 /usr/bin/python

RUN pip install --no-cache-dir \
    torchcodec==0.7 \
    gradio==5.49.1 \
    transformers-stream-generator==0.0.5 \
    accelerate==1.7.0 \
    flash-attn==2.7.4.post1

RUN pip install --no-cache-dir \
    addict==2.4.0 \
    annotated-doc==0.0.4 \
    beautifulsoup4==4.14.3 \
    boxmot==21.0.0 \
    click==8.4.1 \
    deepspeed==0.18.1 \
    contourpy==1.3.3 \
    wandb==0.28.0 \
    cryptography==48.0.0 \
    cycler==0.12.1 \
    defusedxml==0.7.1 \
    filterpy==1.4.5 \
    fonttools==4.63.0 \
    ftfy==6.3.1 \
    gdown==5.2.2 \
    google-auth==2.53.0 \
    google-genai==2.7.0 \
    hf-xet==1.5.0 \
    jsonpatch==1.33 \
    jsonpointer==3.1.1 \
    kiwisolver==1.5.0 \
    langchain==1.3.2 \
    peft==0.17.1 \
    langchain-core==1.4.0 \
    langchain-openai==1.2.2 \
    langchain-protocol==0.0.16 \
    langgraph==1.2.2 \
    langgraph-checkpoint==4.1.1 \
    langgraph-prebuilt==1.1.0 \
    langgraph-sdk==0.3.15 \
    langsmith==0.8.8 \
    lapx==0.9.4 \
    matplotlib==3.10.9 \
    openai==2.38.0 \
    "opencv-python==4.13.0.92" \
    ormsgpack==1.12.2 \
    polars==1.41.2 \
    pyasn1==0.6.3 \
    pyasn1_modules==0.4.2 \
    pycocotools==2.0.11 \
    pyDeprecate==0.7.0 \
    pyparsing==3.3.2 \
    PySocks==1.7.1 \
    regex==2026.5.9 \
    rich==15.0.0 \
    soupsieve==2.8.4 \
    supervision==0.28.0 \
    tenacity==9.1.4 \
    typer==0.25.1 \
    "ultralytics==8.4.60" \
    ultralytics-thop==2.0.19 \
    uuid_utils==0.16.0 \
    wcwidth==0.7.0 \
    yacs==0.1.8 \
    yapf==0.43.0 \
    zstandard==0.25.0

COPY . /workspace/TAU-Agent/


RUN pip install --no-cache-dir \
    "huggingface_hub==0.36.2" \
    "bert-score==0.3.13"

RUN pip install --no-cache-dir -e /workspace/TAU-Agent/transformers && \
    pip install --no-cache-dir -e /workspace/TAU-Agent/qwen-vl-utils && \
    pip install --no-cache-dir -e /workspace/TAU-Agent/trl